
import re
import os
import unicodedata
import sys

from pyquery import PyQuery as pq
from lxml import etree

from pyglossary.glossary import Glossary

from dictmaster.replacer import *
from dictmaster.plugins.bgl import BglProcessor, Plugin as BglPlugin

symbol_img = {}

image_to_html = {
    "033E5C32.png": "<num>36</num>",
    "067AD824.png": "ζ",
    "06B6155D.png": "<num>29</num>",
    "078CEC83.png": "<num>65</num>",
    "07CBF0B5.png": "<num>12</num>",
    "0B046617.png": "<num>35</num>",
    "0D091428.png": "ā′",
    "0E220CA9.png": "<num>54</num>",
    "0F0935C6.png": "<num>72</num>",
    "10154555.png": "<num>20</num>",
    "12AEDB40.png": "<num>62</num>",
    "13878E66.png": "ɛ̃",
    "14D02161.png": "<num>60</num>",
    "15DDFC2F.png": "<num>11</num>",
    "16A4D91A.png": "<num>58</num>",
    "1B562ECC.png": "<num>6</num>",
    "1CC23B58.png": "ǽ",
    "1E820912.png": "ṛ",
    "1E904884.png": "ĝ",
    "1EC80CDC.png": "<num>4</num>",
    "1F32A8C1.png": "<num>40</num>",
    "22630041.png": "ý",
    "23668C38.png": "<num>70</num>",
    "25AEC118.png": "<num>63</num>",
    "2D03EE32.png": "<num>33</num>",
    "2D0A6491.png": "<num>8</num>",
    "2DB704D8.png": "ṣ",
    "2E5132D5.png": "<num>50</num>",
    "2ECA037B.png": "<num>48</num>",
    "33664A42.png": "<u>k</u>",
    "36DE5C0E.png": "<num>27</num>",
    "36E5D4EC.png": "<num>71</num>",
    "3BD7D11B.png": "α",
    "3E9BFA00.png": "<num>28</num>",
    "40439ED5.png": "<u>p</u>",
    "4465D21F.png": "<num>19</num>",
    "448D5880.png": "<num>38</num>",
    "46C75327.png": "<num>41</num>",
    "4A83246D.png": "<num>17</num>",
    "4A91A94C.png": "<num>24</num>",
    "4D6F6F17.png": "<num>55</num>",
    "4DA4D060.png": "Ξ",
    "4E140796.png": "β",
    "51048A3C.png": "<num>9</num>",
    "5196E2B9.png": "aṇ",
    "54913B96.png": "<num>39</num>",
    "54B57139.png": "<num>16</num>",
    "575A1B95.png": "m̀",
    "5CEA5523.png": "ȥ",
    "5DA84A2B.png": "<num>73</num>",
    "601C9445.png": "🟥",
    "613E6948.png": "<num>52</num>",
    "61413BDE.png": "ḥ",
    "64D6FD30.png": "<num>7</num>",
    "65540E1F.png": "<num>75</num>",
    "655E48A1.png": "<num>66</num>",
    "68C52A72.png": "<num>53</num>",
    "6AF2E0F1.png": "<num>42</num>",
    "6B13855A.gif": "⮕",
    "6B316968.png": "<num>22</num>",
    "6B7E0D98.png": "<num>76</num>",
    "6BBB9869.png": "ḷ",
    "6D960BDB.png": "<num>15</num>",
    "73115627.png": "y",
    "73537FF9.png": "<num>68</num>",
    "73BCCB79.png": "˝",
    "74D4394D.png": "<num>74</num>",
    "75068C39.png": "ɔ̃",
    "7530B1E9.png": "ḍ",
    "761C48F2.png": "ȳ",
    "79D460E7.png": "ı",
    "7A57D6A6.png": "ṭ",
    "7A9F3E8D.png": "<num>23</num>",
    "7BC516DA.png": "ƿ",
    "7BD4F2D2.png": "ǵ",
    "7CFAAC1C.png": "<num>44</num>",
    "80723112.png": "<num>25</num>",
    "878C32BA.png": "Ι",
    "8B4F6768.png": "<num>13</num>",
    "8DE97389.png": "ł",
    "8EE91A76.png": "ŷ",
    "911C7ED6.png": "<num>43</num>",
    "92C42472.png": "<num>56</num>",
    "94E6452A.png": "<num>67</num>",
    "95D5C9C1.png": "<num>1</num>",
    "97253D35.png": "<num>47</num>",
    "9D50910E.png": "ṃ",
    "9F2C548A.png": "¨",
    "A206E8EF.png": "<num>57</num>",
    "A2F0D98E.png": "<num>69</num>",
    "A33C7BD5.png": "<num>2</num>",
    "A7572633.png": "<num>34</num>",
    "AA37F35E.png": "​ɥ̄",
    "ABACDED3.png": "<num>26</num>",
    "AC1CC18C.png": "ṇ",
    "B1DAF5F2.png": "<num>30</num>",
    "B30C8A60.png": "<num>46</num>",
    "B665E39E.png": "<num>3</num>",
    "B70DD809.png": "<num>10</num>",
    "BA210F37.png": "<num>51</num>",
    "BAACA594.png": "<num>45</num>",
    "BD30FB9E.png": "†",
    "BE7CFA23.png": "ḇ",
    "C3788D34.png": "χ",
    "C6D1B5ED.png": "õ",
    "C7273B76.png": "ʎ̋",
    "CA410C78.png": "Ƿ",
    "CB62C898.png": "<num>77</num>",
    "CBAEB70A.png": "<num>59</num>",
    "D0404B0F.png": "π",
    "D9B24F2F.png": "ṯ",
    "DAE5A796.png": "<num>64</num>",
    "DB76441D.png": "<num>5</num>",
    "DD7A55CE.png": "ḏ",
    "DF9CF88F.png": "ã",
    "E015965B.png": "<num>37</num>",
    "E5697797.png": "ξ",
    "E8834AC7.png": "<num>31</num>",
    "EDFE4565.png": "<num>21</num>",
    "EE97FFFE.png": "<num>14</num>",
    "F1AEE882.png": "‖",
    "F85AA2C3.png": "<num>32</num>",
    "F91A17C6.png": "ṇ",
    "F9B6D84F.png": "ʎ",
    "FB3FB916.png": "<num>61</num>",
    "FBD9D165.png": "​œ",
    "FE0C60F5.png": "<num>49</num>",
    "FEB6347F.png": "<num>18</num>",
}

entity_table = {
    "3on4": "¾",
    "Asg": "Ʒ",
    "Bantuo": "&lsaquo;Bantuo&rsaquo;",
    "Car": "&lsaquo;Car&rsaquo;",
    "Cced": "Ç",
    "Chirho": "☧",
    "Csigma": "Ϛ",
    "Csub": "&sube;",
    "Edh": "Ð",
    "Hbrbl": "Ḫ",
    "Iasper": "Ἱ",
    "Iasperacu": "Ἵ",
    "Ilenis": "Ἰ",
    "Ilenisacu": "Ἴ",
    "Integ": "∫",
    "Koppa": "Ϟ",
    "Lbar": "Ł",
    "Naira": "N",
    "Nplus": "N",
    "Obar": "Ø",
    "Sced": "Ş",
    "Summ": "∑",
    "Th": "Þ",
    "Thbar": "&lsaquo;Thbar&rsaquo;",
    "Tse": "Ц",
    "Ubox": "&lsaquo;Ubox&rsaquo;",
    "Wyn": "ƿ",
    "Ygh": "Ʒ",
    "Zh": "Ʒ",
    "a": "a",
    "aacuced": "&lsaquo;aacuced&rsaquo;",
    "aced": "&lsaquo;aced&rsaquo;",
    "albrtime": "&lsaquo;albrtime&rsaquo;",
    "aleph": "&alefsym;",
    "alphagra": "ὰ",
    "angle": "∠",
    "ankh": "☥",
    "ante": "a",
    "aonq": "&lsaquo;aonq&rsaquo;",
    "appreq": "≃",
    "aquar": "♒",
    "arDadfull": "ض",
    "arHa": "ح",
    "arTa": "ت",
    "arain": "ع",
    "arainfull": "ع",
    "aralif": "ا",
    "arba": "ب",
    "ardal": "ﺩ",
    "arha": "ه",
    "aries": "♈",
    "arnun": "ن",
    "arnunfull": "ن",
    "arpa": "ه",
    "arqoph": "ق",
    "arshinfull": "ش",
    "arta": "ت",
    "artafull": "ت",
    "artha": "ث",
    "arwaw": "و",
    "arya": "ي",
    "aryafull": "ي",
    "arzero": "٠",
    "asg": "ʒ",
    "assert": "⊢",
    "assyrH": "Ḫ",
    "astm": "⁂",
    "at": "@",
    "ayin": "ع",
    "ayindotab": "ﻍ",
    "ayinold": "ﻋ",
    "b1": "-",
    "b2": "=",
    "b3": "≡",
    "bantuo": "&lsaquo;bantuo&rsaquo;",
    "bbar": "ƀ",
    "bbc1": "|",
    "bbc2": "‖",
    "bbl1": "&lsaquo;bbl1&rsaquo;",
    "bbr1": "&lsaquo;bbr1&rsaquo;",
    "bbr2": "&lsaquo;bbr2&rsaquo;",
    "bcop1": "&lsaquo;bcop1&rsaquo;",
    "bcop2": "&lsaquo;bcop2&rsaquo;",
    "bcurl": "b",
    "benchm": "&lsaquo;benchm&rsaquo;",
    "bigobl": "/",
    "blambda": "𝛌",
    "bLambda": "𝚲",
    "blC": "C",
    "blJ": "J",
    "blU": "U",
    "blb": "b",
    "blozenge": "◊",
    "bly": "y",
    "bra": "&lsaquo;bra&rsaquo;",
    "bslash": "\\",
    "bsquare": "■",
    "btc1": "&lsaquo;btc1&rsaquo;",
    "btc2": "&lsaquo;btc2&rsaquo;",
    "btl1": "&lsaquo;btl1&rsaquo;",
    "btr1": "&lsaquo;btr1&rsaquo;",
    "btr2": "&lsaquo;btr2&rsaquo;",
    "btril": "◀",
    "btrir": "▶",
    "burman": "&lsaquo;burman&rsaquo;",
    "c": "c",
    "cab": "〉",
    "canc": "♋",
    "capr": "♑",
    "car": "↺",
    "caret": "^",
    "cb": "}",
    "cbigb": "}",
    "cbigpren": ")",
    "cbigsb": "]",
    "cced": "ç",
    "cdsb": "〛",
    "chsign": "ъ",
    "circa": "c",
    "circbl": "̥",
    "circle": "○",
    "circledot": "⊙",
    "cjat": "b",
    "clenis": "&lsaquo;clenis&rsaquo;",
    "click": "ʖ",
    "club": "♣",
    "comtime": "C",
    "congr": "&cong;",
    "conj": "☌",
    "cprt": "©",
    "cq": "'",
    "cqq": "”",
    "cross": "✠",
    "crotchet": "♩",
    "csb": "]",
    "cssign": "ь",
    "ctlig": "&lsaquo;ctlig&rsaquo;",
    "cursived": "&part;",
    "cyrO": "О",
    "cyrP": "П",
    "cyra": "а",
    "cyrd": "д",
    "cyre": "е",
    "cyrhard": "ъ",
    "cyrjat": "ѣ",
    "cyrm": "м",
    "cyrn": "н",
    "cyrr": "р",
    "cyrsoft": "ь",
    "cyrt": "т",
    "cyry": "ы",
    "dag": "†",
    "dbar": "đ",
    "dblar": "⇋",
    "dblgt": "≫",
    "dbllt": "≪",
    "dced": "d",
    "dd": "‥",
    "ddag": "‡",
    "ddd": "&hellip;",
    "decr": "↓",
    "dele": "d",
    "descnode": "☋",
    "devdh": "ध",
    "devph": "फ",
    "devrfls": "ष",
    "devrt": "ट",
    "devrth": "ठ",
    "devt": "त",
    "devth": "थ",
    "diam": "♢",
    "diamond": "♢",
    "digamma": "ϝ",
    "Digamma": "Ϝ",
    "ditto": "&lsaquo;ditto&rsaquo;",
    "div": "÷",
    "dlessi": "ı",
    "dlessj1": "j",
    "dlessj2": "j",
    "dlessj3": "j",
    "dollar": "$",
    "drachm": "ʒ",
    "dubh": "-",
    "duplong1": "&lsaquo;duplong1&rsaquo;",
    "duplong2": "&lsaquo;duplong2&rsaquo;",
    "earth": "♁",
    "edh": "ð",
    "egchi": "&lsaquo;egchi&rsaquo;",
    "eggamma1": "&lsaquo;eggamma1&rsaquo;",
    "eggamma2": "&lsaquo;eggamma2&rsaquo;",
    "egiota": "&lsaquo;egiota&rsaquo;",
    "egkappa": "&lsaquo;egkappa&rsaquo;",
    "eglambda": "&lsaquo;eglambda&rsaquo;",
    "egmu1": "&lsaquo;egmu1&rsaquo;",
    "egmu2": "&lsaquo;egmu2&rsaquo;",
    "egnu1": "&lsaquo;egnu1&rsaquo;",
    "egnu2": "&lsaquo;egnu2&rsaquo;",
    "egpi1": "&lsaquo;egpi1&rsaquo;",
    "egpi2": "&lsaquo;egpi2&rsaquo;",
    "egpi3": "&lsaquo;egpi3&rsaquo;",
    "egrho1": "&lsaquo;egrho1&rsaquo;",
    "egrho2": "&lsaquo;egrho2&rsaquo;",
    "egsampi": "&lsaquo;egsampi&rsaquo;",
    "egsan": "&lsaquo;egsan&rsaquo;",
    "egsigma1": "&lsaquo;egsigma1&rsaquo;",
    "egsigma2": "&lsaquo;egsigma2&rsaquo;",
    "egxi1": "&lsaquo;egxi1&rsaquo;",
    "egxi2": "&lsaquo;egxi2&rsaquo;",
    "egxi3": "&lsaquo;egxi3&rsaquo;",
    "egy3": "&lsaquo;egy3&rsaquo;",
    "egyasper": "&lsaquo;egyasper&rsaquo;",
    "elatS": "&lsaquo;elatS&rsaquo;",
    "elatc1": "&lsaquo;elatc1&rsaquo;",
    "elatc2": "&lsaquo;elatc2&rsaquo;",
    "elatg1": "&lsaquo;elatg1&rsaquo;",
    "elatg2": "&lsaquo;elatg2&rsaquo;",
    "elem": "∊",
    "em": "—",
    "emem": "―",
    "en": "–",
    "equil": "⇋",
    "ergo": "∴",
    "eszett": "ß",
    "expon": "↑",
    "fac": "&lsaquo;fac&rsaquo;",
    "fact": "!",
    "fata": "ɑ",
    "fatatilde": "&lsaquo;fatatilde&rsaquo;",
    "fatpara": "¶",
    "female": "♀",
    "ffilig": "ﬃ",
    "ffllig": "ﬄ",
    "flat": "♭",
    "fllig": "ﬂ",
    "fourd": "&lsaquo;fourd&rsaquo;",
    "frE": "E",
    "frL": "L",
    "frR": "R",
    "frakB": "B",
    "frakE": "&lsaquo;frakE&rsaquo;",
    "frakF": "&lsaquo;frakF&rsaquo;",
    "frakG": "G",
    "frakH": "H",
    "frakI": "I",
    "frakK": "&lsaquo;frakK&rsaquo;",
    "frakL": "&lsaquo;frakL&rsaquo;",
    "frakM": "M",
    "frakP": "&lsaquo;frakP&rsaquo;",
    "frakR": "&real;",
    "frakU": "U",
    "frakX": "X",
    "frakY": "Y",
    "frakg": "&lsaquo;frakg&rsaquo;",
    "frakh": "h",
    "fs": " ",
    "fsigma": "ς",
    "fslash": "/",
    "gbbelow": "g",
    "gjat": "",
    "glagjat": "ѧ",
    "glagjer": "&lsaquo;glagjeri&rsaquo;",
    "glagjeri": "&lsaquo;glagjeri&rsaquo;",
    "glagjeru": "&lsaquo;glagjeru&rsaquo;",
    "gjeri": "Ⱐ",
    "gjeru": "Ⱏ",
    "glots": "ˀ",
    "half": "&frac12;",
    "halft": "⌈",
    "hamza": "ﺀ",
    "hash": "#",
    "hatpath": "ֲ",
    "hatqam": "ֳ",
    "hatseg": "ֱ",
    "hbar": "ħ",
    "hbrbl": "ḫ",
    "heart": "♡",
    "hebaleph": "א",
    "hebayin": "ע",
    "hebbet": "ב",
    "hebbeth": "ב",
    "hebcheth": "ח",
    "hebdaleth": "ד",
    "hebgimel": "ג",
    "hebhe": "ה",
    "hebkaph": "כ",
    "heblamed": "ל",
    "hebmem": "מ",
    "hebnun": "נ",
    "hebnunfin": "ן",
    "hebpe": "פ",
    "hebpedag": "ף",
    "hebqoph": "ק",
    "hebresh": "ר",
    "hebshin": "ש",
    "hebtav": "ת",
    "hebteth": "ט",
    "hebtsade": "צ",
    "hebwaw": "ו",
    "hebyod": "י",
    "hebzayin": "ז",
    "hgz": "ʒ",
    "hireq": "ִ",
    "horizE": "E",
    "horizP": "P",
    "horizS": "∽",
    "horizT": "⊣",
    "horizb": "{",
    "huncU": "&lsaquo;huncU&rsaquo;",
    "hypolem": "&lsaquo;hypolem&rsaquo;",
    "ia": "α",
    "iasper": "ἱ",
    "iasperacu": "ἵ",
    "iasperfrown": "ἷ",
    "ib": "β",
    "ibar": "ɨ",
    "iced": "&lsaquo;iced&rsaquo;",
    "id": "δ",
    "ident": "≡",
    "ie": "ε",
    "ifflig": "ﬀ",
    "ifilig": "ﬁ",
    "ifrbl": "&lsaquo;ifrbl&rsaquo;",
    "ig": "γ",
    "igra": "ì",
    "ih": "η",
    "ii": "ι",
    "ik": "κ",
    "ilenis": "ἰ",
    "ilenisacu": "ἴ",
    "ilenisfrown": "ἶ",
    "ilenismac": "&lsaquo;ilenismac&rsaquo;",
    "ilenismacacu": "&lsaquo;ilenismacacu&rsaquo;",
    "implies": "⇒",
    "index": "☞",
    "integ": "∫",
    "intsec": "∩",
    "intset": "ℤ",
    "invpri": "ˏ",
    "iq": "ψ",
    "istlig": "ﬆ",
    "isub": "ϵ",
    "italU": "&lsaquo;italU&rsaquo;",
    "iz": "ζ",
    "jup": "♃",
    "koppa": "ϟ",
    "lar": "←",
    "lbar": "ł",
    "lbelt": "&lsaquo;lbelt&rsaquo;",
    "lcircbl": "&lsaquo;lcircbl&rsaquo;",
    "lenis": "᾿",
    "leo": "♌",
    "lhalfbr": "⌈",
    "lhshoe": "⊃",
    "libra": "♎",
    "llswing": "&lsaquo;llswing&rsaquo;",
    "lm": "ː",
    "logicand": "∧",
    "logicor": "∨",
    "longmord": "&lsaquo;longmord&rsaquo;",
    "longs": "ʃ",
    "lrar": "↔",
    "ltappr": "≾",
    "ltflat": "∠",
    "ltlt": "≪",
    "lumlbl": "l",
    "male": "♂",
    "mbwvow": "&lsaquo;mbwvow&rsaquo;",
    "mc": "c",
    "mcircbl": "&lsaquo;mcircbl&rsaquo;",
    "merc": "☿",
    "mfrown": "&lsaquo;mfrown&rsaquo;",
    "min": "−",
    "minpl": "∓",
    "moonfq": "☽",
    "moonlq": "☾",
    "mord": "&lsaquo;mord&rsaquo;",
    "mostra": "&lsaquo;mostra&rsaquo;",
    "msylab": "m",
    "msyllab": "&lsaquo;msyllab&rsaquo;",
    "natural": "♮",
    "nb": "",
    "ncircbl": "&lsaquo;ncircbl&rsaquo;",
    "neq": "≠",
    "nfacu": "′",
    "nfasp": "ʻ",
    "nfasper": "ʻ",
    "nfbreve": "˘",
    "nfced": "¸",
    "nfcirc": "ˆ",
    "nffrown": "⌢",
    "nfgra": "ˋ",
    "nfhacek": "ˇ",
    "nflenis": "᾿",
    "nfmac": "¯",
    "nftilde": "˜",
    "nfuml": "¨",
    "nfundl": "&lsaquo;nfundl&rsaquo;",
    "ng": "ŋ",
    "nono": "&lsaquo;nono&rsaquo;",
    "notelem": "∉",
    "nowy": "&lsaquo;nowy&rsaquo;",
    "oab": "〈",
    "ob": "{",
    "obar": "ø",
    "obaracu": "ǿ",
    "obarmac": "&lsaquo;obarmac&rsaquo;",
    "obigb": "{",
    "obigpren": "(",
    "obigsb": "[",
    "odsb": "〚",
    "oeamp": "&",
    "ohgcirc": "&lsaquo;ohgcirc&rsaquo;",
    "oldbeta": "&lsaquo;oldbeta&rsaquo;",
    "oldsemibr1": "&lsaquo;oldsemibr1&rsaquo;",
    "oldsemibr2": "&lsaquo;oldsemibr2&rsaquo;",
    "oneon3": "⅓",
    "oneon4": "¼",
    "oneth": "Ð",
    "ope": "ɛ",
    "opemac": "&lsaquo;opemac&rsaquo;",
    "opetilde": "&lsaquo;opetilde&rsaquo;",
    "opp": "☍",
    "oq": "`",
    "oqq": "“",
    "ormg": "&lsaquo;ormg&rsaquo;",
    "osb": "[",
    "ounce": "℥",
    "ovparen": "⌢",
    "p": "′",
    "pa": "∂",
    "page": "P",
    "pall": "ʎ",
    "paln": "ɲ",
    "para2": "&lsaquo;para2&rsaquo;",
    "para3": "&lsaquo;para3&rsaquo;",
    "para4": "&lsaquo;para4&rsaquo;",
    "para5": "&lsaquo;para5&rsaquo;",
    "pauseo": "&lsaquo;pauseo&rsaquo;",
    "pauseu": "&lsaquo;pauseu&rsaquo;",
    "pbar": "p",
    "pcnt": "%",
    "per": "℘",
    "pharyng": "ʕ",
    "phi2": "ϕ",
    "pisces": "♓",
    "planck": "ħ",
    "plantinJ": "J",
    "pm": "±",
    "pmil": "‰",
    "pp": "″",
    "ppp": "‴",
    "psense": "▸",
    "pstlg": "£",
    "q": "?",
    "qamets": "ֳ",
    "quaver": "♪",
    "ragr": "&lsaquo;ragr&rsaquo;",
    "rar": "→",
    "rash": "ᚨ",
    "rbbelow": "t",
    "rcircbl": "&lsaquo;rcircbl&rsaquo;",
    "rcircblmac": "&lsaquo;rcircblmac&rsaquo;",
    "rdot": "·",
    "recipe": "℞",
    "repetn": "&lsaquo;repetn&rsaquo;",
    "revsc": "˒",
    "rfa": "o",
    "rfatilde": "&lsaquo;rfatilde&rsaquo;",
    "rglots": "ʕ",
    "rhalfbr": "⌉",
    "rhshoe": "⊂",
    "roasper": "&lsaquo;roasper&rsaquo;",
    "rsylab": "r",
    "rsyllab": "&lsaquo;rsyllab&rsaquo;",
    "ruasper": "&lsaquo;ruasper&rsaquo;",
    "runash": "F",
    "runicwynn": "ᚹ",
    "runwyn": "ᚹ",
    "rvow": "˔",
    "sagit": "♐",
    "sampi": "ϡ",
    "saturn": "♄",
    "sced": "ş",
    "schwafrbl": "&lsaquo;schwafrbl&rsaquo;",
    "scl": "ʟ",
    "scorpio": "♏",
    "scrA": "A",
    "scrC": "C",
    "scrD": "&lsaquo;scrD&rsaquo;",
    "scrE": "E",
    "scrF": "F",
    "scrI": "I",
    "scrJ": "J",
    "scrL": "L",
    "scrM": "ℳ",
    "scrO": "O",
    "scrP": "P",
    "scrQ": "Q",
    "scrR": "ℛ",
    "scrS": "S",
    "scrT": "T",
    "scrU": "&lsaquo;scrU&rsaquo;",
    "scrb": "b",
    "scrd": "d",
    "scrh": "h",
    "scrl": "l",
    "scruple": "℈",
    "sdd": "ː",
    "segno": "&lsaquo;segno&rsaquo;",
    "segol": "ֶ",
    "semE": "∃",
    "semain1": "&lsaquo;semain1&rsaquo;",
    "semain2": "&lsaquo;semain2&rsaquo;",
    "semhe": "&lsaquo;semhe&rsaquo;",
    "semheth": "&lsaquo;semheth&rsaquo;",
    "semibr": "&lsaquo;semibr&rsaquo;",
    "semkaph": "&lsaquo;semkaph&rsaquo;",
    "semlamed1": "&lsaquo;semlamed1&rsaquo;",
    "semlamed2": "&lsaquo;semlamed2&rsaquo;",
    "semmem": "&lsaquo;semmem&rsaquo;",
    "semnun": "&lsaquo;semnun&rsaquo;",
    "sempe": "&lsaquo;sempe&rsaquo;",
    "semqoph1": "&lsaquo;semqoph1&rsaquo;",
    "semqoph2": "&lsaquo;semqoph2&rsaquo;",
    "semqoph3": "&lsaquo;semqoph3&rsaquo;",
    "semresh": "&lsaquo;semresh&rsaquo;",
    "semtav1": "&lsaquo;semtav1&rsaquo;",
    "semtav2": "&lsaquo;semtav2&rsaquo;",
    "semtav3": "&lsaquo;semtav3&rsaquo;",
    "semtav4": "&lsaquo;semtav4&rsaquo;",
    "semyod": "&lsaquo;semyod&rsaquo;",
    "semzayin1": "&lsaquo;semzayin1&rsaquo;",
    "semzayin2": "&lsaquo;semzayin2&rsaquo;",
    "semzayin3": "&lsaquo;semzayin3&rsaquo;",
    "sh": "ʃ",
    "shadda": "ﹼ",
    "sharp": "♯",
    "sheva": "ְ",
    "shti": "ɪ",
    "shtibar": "ɪ",
    "shtlong1": "&lsaquo;shtlong1&rsaquo;",
    "shtlong2": "&lsaquo;shtlong2&rsaquo;",
    "shtsyll": "∪",
    "shtsyllmac": "&lsaquo;shtsyllmac&rsaquo;",
    "shtu": "ʊ",
    "sidetri": "⊲",
    "sigmatau": "ϛ",
    "since": "∵",
    "sixon2": "6/2",
    "sixon4": "6/4",
    "sixon8": "6/8",
    "slge": "≥",
    "slle": "≤",
    "sm": "ˈ",
    "smR": "ʀ",
    "smY": "ʏ",
    "smm": "ˌ",
    "sp": "",
    "spade": "♠",
    "sqbreve": "&lsaquo;sqbreve&rsaquo;",
    "sqquav": "&lsaquo;sqquav&rsaquo;",
    "sqrt": "√",
    "square": "□",
    "squaver": "&lsaquo;squaver&rsaquo;",
    "ssChi": "Χ",
    "ssIota": "Ι",
    "ssOmicron": "Ο",
    "ssPi": "Π",
    "ssRho": "Ρ",
    "ssSigma": "Σ",
    "ssTau": "Τ",
    "star": "*",
    "stlig": "ﬅ",
    "sun": "☉",
    "subsr": "→",
    "supa": "<sup>a</sup>",
    "supc": "<sup>c</sup>",
    "supd": "<sup>d</sup>",
    "supg": "<sup>g</sup>",
    "supgt": "˃",
    "suph": "<sup>h</sup>",
    "supi": "<sup>i</sup>",
    "supl": "<sup>l</sup>",
    "suplt": "˂",
    "supm": "<sup>m</sup>",
    "supr": "<sup>r</sup>",
    "sups": "<sup>s</sup>",
    "supt": "<sup>t</sup>",
    "supu": "<sup>u</sup>",
    "supw": "<sup>w</sup>",
    "supy": "<sup>y</sup>",
    "supz": "<sup>z</sup>",
    "sur": "ʳ",
    "swast": "&lsaquo;swast&rsaquo;",
    "swing": "∼",
    "taur": "♉",
    "tced": "ţ",
    "th": "þ",
    "thbar": "þ",
    "thdotab": "&lsaquo;thdotab&rsaquo;",
    "thinqm": "?",
    "threeon16": "3/16",
    "threeon2": "3/2",
    "threeon4": "¾",
    "threeon8": "⅜",
    "tie": "&lsaquo;tie&rsaquo;",
    "tittle": "⋰",
    "tri": "∆",
    "trli": "‖",
    "ts": "\u2009",
    "two2n": "&lsaquo;two2n&rsaquo;",
    "twoon4": "2/4",
    "twothird": "⅔",
    "ubar": "u",
    "udA": "∀",
    "udT": "⊥",
    "uda": "ɐ",
    "udatilde": "&lsaquo;udatilde&rsaquo;",
    "udh": "ɥ",
    "udpsi": "⋔",
    "udqm": "¿",
    "udtr": "∇",
    "udw": "ʍ",
    "ufrbl": "&lsaquo;ufrbl&rsaquo;",
    "uncU": "&lsaquo;uncU&rsaquo;",
    "undl": "ˍ",
    "union": "∪",
    "uumlsc": "ü",
    "vavpath": "ו",
    "vavsheva": "ו",
    "vb": "|",
    "vddd": "⋮",
    "vdftheta": "&theta;",
    "versicle1": "℣",
    "versicle2": "℣",
    "vinc": "¯",
    "virgo": "♍",
    "vpal": "ɟ",
    "vvf": "ɣ",
    "wapos": "&lsaquo;wapos&rsaquo;",
    "wavyeq": "≈",
    "woqab": "&lsaquo;woqab&rsaquo;",
    "wyn": "ƿ",
    "ye": "&lsaquo;ye&rsaquo;",
    "ygh": "ʒ",
    "yt": "&lsaquo;yt&rsaquo;",
    "zbbelow": "j",
    "zced": "z",
}
"""Replacements for non-standard entities (special characters)

From https://plan9.io/sources/plan9/sys/src/cmd/dict/oed.c
merged with https://github.com/Barjak/OED_unpack_tools.py/blob/master/parse.py
and without HTML entites in `html.entities.entitydefs`
"""

extra_letters = {
    "ae": "æ",
    "Ae": "Æ",
    "nu": "ν",
    "oe": "œ",
    "Oe": "Œ",
    "reva": "ɒ",
    "revC": "Ɔ",
    "revc": "ɔ",
    "revope": "ɜ",
    "revr": "ɹ",
    "revv": "ʌ",
    "schwa": "ə",
    "zh": "ʒ",
}
combine_chars = {
    "acu": "\u0301",
    "acdbl": "\u030b",
    "ang": "\u030a",
    "bar": "\u0304",
    "barab": "\u0304",
    "bbelow": "\u0332",
    "breve": "\u0306",
    "circsc": "\u0302",
    "circ": "\u0302",
    "dabove": "\u0307",
    "dbelow": "\u0323",
    "dotab": "\u0307",
    "dotbl": "\u0323",
    "grave": "\u0300",
    "gravdbl": "\u030f",
    "gra": "\u0300",
    "hacekb": "\u030c",
    "hacek": "\u030c",
    "hook": "\u0328",
    "mac": "\u0304",
    "tildepr": "\u0303",
    "tilde": "\u0303",
    "umlsc": "\u0308",
    "uml": "\u0308",
    "undl": "\u0332",
    "undtilde": "\u0330",
}
combine_chars_re = "(?:" + "|".join(combine_chars.keys()) + ")"
combine_chars_re_extra = (
    f"(?i)^([a-z]|{'|'.join(extra_letters.keys())})({combine_chars_re}+)$"
)
extra_letters_grk = {
    "aa": "α",
    "Aa": "Α",
    "ga": "α",
    "gA": "Α",
    "a": "α",
    "A": "Α",
    "ge": "ε",
    "gh": "η",
    "gi": "ι",
    "go": "ο",
    "gu": "υ",
    "gw": "ω",
    "e": "ε",
    "E": "Ε",
    "h": "η",
    "H": "Η",
    "w": "ω",
    "W": "Ω",
    "u": "υ",
    "U": "Υ",
    "r": "ρ",
    "R": "Ρ",
    "o": "ο",
    "O": "Ο",
}
combine_chars_grk = {
    **combine_chars,
    "asper": "\u0485",
    "frownb": "\u0342",
    "frown": "\u0342",
    "isub": "\u0345",
    "lenis": "\u0486",
}
combine_chars_grk_re = "(?:" + "|".join(combine_chars_grk.keys()) + ")"
combine_chars_grk_re_extra = (
    f"(?i)^({'|'.join(extra_letters_grk.keys())})({combine_chars_grk_re}+)$"
)

def _grk_entity_name_to_unicode(ent):
    ent = re.sub(r"^epsilon", "ge", ent)
    ent = re.sub(r"^eta", "gh", ent)
    m = re.match(combine_chars_grk_re_extra, ent)
    if m is None:
        return None
    res = m.group(1)
    for r1, r2 in extra_letters_grk.items():
        res = res.replace(r1, r2)
    combs = m.group(2)
    l_combs = len(combs)
    for m in re.finditer(combine_chars_grk_re, combs):
        cc = m.group(0)
        res += combine_chars_grk[cc]
        l_combs -= len(cc)
    if l_combs > 0:
        print(ent, combs, res)
        sys.exit()
    return unicodedata.normalize("NFC", res)

def entity_name_to_unicode(ent):
    if ent in extra_letters:
        return extra_letters[ent]
    m = re.match(combine_chars_re_extra, ent)
    if m is None:
        return _grk_entity_name_to_unicode(ent)
    res = m.group(1)
    for r1, r2 in extra_letters.items():
        res = res.replace(r1, r2)
    combs = m.group(2)
    for m in re.finditer(combine_chars_re, combs):
        res += combine_chars[m.group(0)]
    return unicodedata.normalize("NFC", res)

class Plugin(BglPlugin):
    def post_setup(self, cursor):
        BglPlugin.post_setup(self, cursor)

        res_dirname = os.path.join(self.output_directory, "res")
        for f in os.listdir(res_dirname):
            if f not in symbol_img and f in image_to_html:
                os.remove(os.path.join(res_dirname, f))
        self.stages['Processor'] = SoedProcessor(self)

class SoedProcessor(BglProcessor):
    def do_bgl_definition(self, definition, term, alts):
        definition = BglProcessor.do_bgl_definition(self, definition, term, alts)

        def cb_fun(m):
            ent = m.group(1)
            if ent in entity_table:
                res = entity_table[ent]
                if res.startswith("&lsaquo;"):
                    print(term)
                    print(ent, res)
                    print(definition.replace(ent, f'\033[93m{ent}\033[0m'))
                    print()
                    # sys.exit()
            else:
                res = entity_name_to_unicode(ent)
                if res is None:
                    print(term)
                    print("Unknown entity", ent)
                    print(definition.replace(ent, f'\033[93m{ent}\033[0m'))
                    print()
                    # sys.exit()
            return res


        re.sub(r"&amp;([A-Za-z0-9]+);", cb_fun, definition)
        definition = re.sub(r"&([^;]+);", r"##\1||", definition)
        parser = etree.HTMLParser(encoding="utf-8")
        doc = pq(etree.fromstring(definition, parser=parser))

        def _replace_img_el(el, doc=doc):
            if doc(el).outerHtml() is None:
                return ""
            assert len(doc(el).parents("strong")) == 0

            img_src = doc(el).attr("src").strip()
            replacement = el
            if img_src in image_to_html:
                replacement = doc("<span/>").html(image_to_html[img_src])
            elif img_src in symbol_img:
                replacement.addClass("_dictmaster_touched")
            else:
                print(term)
                print(img_src)
                print(definition.replace(img_src, f'\033[93m{img_src}\033[0m'))
                sys.exit()
            return replacement
        doc_replace_els(doc, "img:not(._dictmaster_touched)", _replace_img_el)
        doc("img").removeAttr("class")

        new_el = doc("<b/>").css({
            "background-color": "#b55",
            "color": "#fff",
            "padding": "0.1ex 0.5ex 0",
            "margin-right": "0.5ex",
        })
        doc_rewrap_els(doc, "num", new_el.outerHtml(), textify=True)

        definition = doc.html()

        # remove empty strong/div tags
        regex = [
            [r"##([^\|]+)\|\|",r"&\1;"],
            [r"(?i)<(strong|div)[^>]*>\s*</(strong|div)>", ""],
        ]
        for r in regex:
            definition = re.sub(r[0], r[1], definition)

        return doc.html()
